env:
  global:
    - CC_TEST_REPORTER_ID=7333f14d7dec91ddfbe8cc61ba1c6b3cbf4481e39f8e55dd70af599040af1b9c
language: python
email:
    on_success: always
    on_failure: always
python:
 - "3.6"
install:
  - pip install -U --upgrade-strategy eager -r requirements.txt # always use the newest version of packages
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
 - pytest --cov-report xml --cov=generic_parser tests
 - travis-sphinx build --source=doc/ --nowarn
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
 - travis-sphinx deploy
